/** Stable identifiers for IPC and logging — extend as domains grow */
export type ErrorCode =
  | 'CONFIG_READ_FAILED'
  | 'CONFIG_WRITE_FAILED'
  | 'CONFIG_VALIDATION_FAILED'
  | 'CONFIG_DIR_NOT_WRITABLE'
  | 'IPC_HANDLER_FAILED'
  | 'APP_BOOT_TIMEOUT'
  | 'APP_LOAD_FAILED'
  | 'DEV_MOCK'
  | 'HTTP_REQUEST_FAILED'
  | 'HTTP_SCRIPT_TIMEOUT'
  | 'HTTP_OAUTH_FAILED'
  | 'LOAD_TEST_ALREADY_RUNNING'
  | 'LOAD_TEST_TARGET_NOT_FOUND'
  | 'REGRESSION_ALREADY_RUNNING'
  | 'REGRESSION_NOT_FOUND'
  | 'REGRESSION_ARCHIVED';

export type ErrorCodesMap = Record<string, ErrorCode>;

export const ErrorCodes = {
  CONFIG_READ_FAILED: 'CONFIG_READ_FAILED',
  CONFIG_WRITE_FAILED: 'CONFIG_WRITE_FAILED',
  CONFIG_VALIDATION_FAILED: 'CONFIG_VALIDATION_FAILED',
  CONFIG_DIR_NOT_WRITABLE: 'CONFIG_DIR_NOT_WRITABLE',
  IPC_HANDLER_FAILED: 'IPC_HANDLER_FAILED',
  APP_BOOT_TIMEOUT: 'APP_BOOT_TIMEOUT',
  APP_LOAD_FAILED: 'APP_LOAD_FAILED',
  DEV_MOCK: 'DEV_MOCK',
  HTTP_REQUEST_FAILED: 'HTTP_REQUEST_FAILED',
  HTTP_SCRIPT_TIMEOUT: 'HTTP_SCRIPT_TIMEOUT',
  HTTP_OAUTH_FAILED: 'HTTP_OAUTH_FAILED',
  LOAD_TEST_ALREADY_RUNNING: 'LOAD_TEST_ALREADY_RUNNING',
  LOAD_TEST_TARGET_NOT_FOUND: 'LOAD_TEST_TARGET_NOT_FOUND',
  REGRESSION_ALREADY_RUNNING: 'REGRESSION_ALREADY_RUNNING',
  REGRESSION_NOT_FOUND: 'REGRESSION_NOT_FOUND',
  REGRESSION_ARCHIVED: 'REGRESSION_ARCHIVED',
} satisfies ErrorCodesMap;
