import {
  ANIMATION_SPEED_OPTIONS,
  COLLECTION_FOLDER_CLICK_BEHAVIOR_IDS,
  COLLECTION_SIBLING_SORT_IDS,
  LOG_LEVEL_OPTIONS,
  collectionFolderClickBehaviorLabel,
} from '@shared/config';
import {
  THEME_PALETTES,
  THEME_UI_GROUPS,
  UI_FONT_CATALOG,
  UI_FONT_SIZE_OPTIONS,
  UI_FONT_WEIGHT_OPTIONS,
  UI_LINE_HEIGHT_OPTIONS,
} from '@shared/theme';

import { HTTP_METHOD_DISPLAY_OPTIONS } from './sections/tx-settings-http-method-display-options';
import {
  HTTP_METHOD_OPTIONS,
  HTTP_REQUEST_SECTION_OPTIONS,
  HTTP_RESPONSE_TAB_ON_SEND_OPTIONS,
  HTTP_URL_SCHEME_OPTIONS,
} from './sections/tx-settings-http-options';
import { WORKSPACE_EDITOR_LAYOUT_OPTIONS } from './sections/tx-settings-workspace-editor-options';
import type { SettingsPopupSection } from './tx-settings-popup.component';

const COLLECTION_SIBLING_SORT_LABELS: Record<(typeof COLLECTION_SIBLING_SORT_IDS)[number], string> = {
  order: 'Order',
  priority: 'Priority',
  orderThenPriority: 'Order, then priority',
  manual: 'Manual (drag only)',
};

const DATABASE_TYPE_LABELS = [
  'PostgreSQL',
  'MySQL',
  'MariaDB',
  'SQL Server',
  'SQLite',
  'Redis',
] as const;

function optionLabels(
  options: readonly { readonly label: string }[],
): readonly string[] {
  return options.map((entry) => entry.label);
}

function flattenTerms(...groups: readonly (string | readonly string[])[]): readonly string[] {
  const terms: string[] = [];
  for (const group of groups) {
    if (typeof group === 'string') {
      terms.push(group);
      continue;
    }
    terms.push(...group);
  }
  return terms;
}

/** Searchable labels, headings, and option text per settings section. */
const SETTINGS_SECTION_SEARCH_TERMS: Record<SettingsPopupSection, readonly string[]> = {
  appearance: flattenTerms(
    'Appearance',
    'Typography',
    'Theme',
    'Interface font',
    'Size',
    'Weight',
    'Line height',
    'Reset to defaults',
    'palette',
    'Pick a palette by category',
    optionLabels(UI_FONT_CATALOG),
    optionLabels(UI_FONT_SIZE_OPTIONS),
    optionLabels(UI_FONT_WEIGHT_OPTIONS),
    optionLabels(UI_LINE_HEIGHT_OPTIONS),
    THEME_UI_GROUPS.map((group) => group.label),
    THEME_PALETTES.map((palette) => palette.label),
    THEME_PALETTES.map((palette) => palette.id),
  ),
  ui: flattenTerms(
    'User Interface',
    'Navigation',
    'Motion',
    'Animation speed',
    'Tooltips',
    'chrome',
    'Close sidebar panel when clicking outside',
    'Restore last sidebar panel on startup',
    'Show icon tooltips',
    'Translucent title bar',
    'blur',
    'Workbench behavior',
    optionLabels(ANIMATION_SPEED_OPTIONS),
    ANIMATION_SPEED_OPTIONS.map((entry) => entry.id),
  ),
  editorKeyboard: flattenTerms(
    'Keyboard',
    'Behavior',
    'Shortcut reference',
    'Enable keyboard shortcuts',
    'Autocomplete',
    'Ctrl',
    'Cmd',
    'Space',
    'JavaScript Postman API suggestions',
    'Open suggestions after typing',
    'JSON snippet suggestions',
    'Auto-close quotes, brackets, and tags',
    'Smart typing',
    'XML/HTML snippet suggestions',
    'Template variables',
    'environment placeholders',
    'JSON closing quote suggestion',
    'Tab to accept',
  ),
  collections: flattenTerms(
    'Collections',
    'Drag & drop',
    'Sort & priority',
    'Folders',
    'Editor',
    'Display',
    'Expand folder on drag',
    'Move animation',
    'Expand animation',
    'Sibling sort mode',
    'Folders first',
    'Folder click behavior',
    'Editor layout',
    'Show descriptions in tree',
    'Show tags in tree',
    'Display HTTP method',
    COLLECTION_SIBLING_SORT_IDS.map((id) => COLLECTION_SIBLING_SORT_LABELS[id]),
    COLLECTION_FOLDER_CLICK_BEHAVIOR_IDS.map((id) => collectionFolderClickBehaviorLabel(id)),
    optionLabels(WORKSPACE_EDITOR_LAYOUT_OPTIONS),
    optionLabels(HTTP_METHOD_DISPLAY_OPTIONS),
  ),
  environments: flattenTerms(
    'Environments',
    'Drag & drop',
    'Sort & priority',
    'Display',
    'Expand folder on drag',
    'Move animation',
    'Expand animation',
    'Sibling sort mode',
    'Folders first',
    'Show descriptions in tree',
    'Use folder path in variable placeholders',
    COLLECTION_SIBLING_SORT_IDS.map((id) => COLLECTION_SIBLING_SORT_LABELS[id]),
  ),
  testSuite: flattenTerms(
    'Test Suite',
    'Drag & drop',
    'Sort & priority',
    'Display',
    'Expand folder on drag',
    'Move animation',
    'Expand animation',
    'Sibling sort mode',
    'Folders first',
    'Show descriptions in tree',
    'Show tags in tree',
    COLLECTION_SIBLING_SORT_IDS.map((id) => COLLECTION_SIBLING_SORT_LABELS[id]),
  ),
  general: flattenTerms(
    'General',
    'Language',
    'Open last project on startup',
    'startup',
    'project',
  ),
  logging: flattenTerms(
    'Logging',
    'Output',
    'Detail',
    'Retention',
    'Files',
    'Enable logging',
    'Write to log file',
    'Write to console',
    'Include timestamps',
    'Minimum log level',
    'Redact secrets in log lines',
    'Log IPC invocations in dev',
    'Max log file size',
    'Retained log files',
    'Log directory',
    'Recent log lines',
    'Clear log files',
    optionLabels(LOG_LEVEL_OPTIONS),
    LOG_LEVEL_OPTIONS.map((entry) => entry.id),
  ),
  databases: flattenTerms(
    'Database Connections',
    'Databases',
    'Configure connection profiles',
    'test suite flows',
    'flow variables',
    'Add connection',
    'Name',
    'Type',
    'Connect on app startup',
    'File path',
    'Busy timeout',
    'Host',
    'Port',
    'User',
    'Password',
    'Database index',
    'Database name',
    'Use TLS',
    'Connect timeout',
    'Command timeout',
    'Test connection',
    DATABASE_TYPE_LABELS,
  ),
  dataConfig: flattenTerms(
    'Data & Config',
    'Workspace profile',
    'Global settings',
    'Files',
    'Write behavior',
    'Backup & reset',
    'Metadata',
    'Active profile',
    'Profile workspace folder',
    'Open profile folder',
    'Rename profile',
    'Delete profile',
    'Global settings folder',
    'Change global folder',
    'Workspace data folder',
    'Choose workspace folder',
    'settings.json',
    'session.json',
    'collections.json',
    'history.json',
    'Reload configuration',
    'Validate config on startup',
    'Pretty-print JSON when saving',
    'Backup config before write',
    'Reload when files change externally',
    'Export settings',
    'Import settings',
    'Reset settings',
    'Reset session',
    'schema version',
  ),
  httpRequest: flattenTerms(
    'Request',
    'Defaults',
    'Transport',
    'Redirects & SSL',
    'Default HTTP method',
    'Active section when opening request',
    'Default response tab after send',
    'Default URL scheme',
    'Auto-fix URL on send',
    'Add www. for bare domains',
    'Auto-detect Content-Type from request body on send',
    'Timeout',
    'Use cookies',
    'Enable HTTP/2',
    'Fallback to HTTP/1.1',
    'Follow redirects',
    'Strict SSL',
    'Disable cookies globally',
    'Max redirects',
    'Content-Type',
    optionLabels(HTTP_METHOD_OPTIONS),
    optionLabels(HTTP_REQUEST_SECTION_OPTIONS),
    optionLabels(HTTP_RESPONSE_TAB_ON_SEND_OPTIONS),
    optionLabels(HTTP_URL_SCHEME_OPTIONS),
  ),
  httpRetries: flattenTerms(
    'Retries',
    'Retry policy',
    'Backoff',
    'Automatic retry behavior',
    'Exponential backoff',
    'Enabled',
    'Retry amount',
    'Retry delay',
    'Backoff multiplier',
    'Max delay',
  ),
  httpTesting: flattenTerms(
    'Testing',
    'E2E',
    'Screenshot folder',
    'automated',
    'end-to-end test runs',
    'Browse',
  ),
  httpHeaders: flattenTerms(
    'Headers',
    'Apply default headers',
    'dynamic placeholders',
    'uuid',
    'timestamp',
    'randomInt',
    'Preview resolved headers',
    'Add header',
    'Header',
    'Description',
    'Value',
  ),
  httpCertificates: flattenTerms(
    'Certificates & SSL',
    'Certificates',
    'Ignore Invalid SSL',
    'self-signed',
    'Verify Hostname',
    'Managed certificates',
    'client cert',
    'mTLS',
    'Hostname',
    'Passphrase',
    'Add Certificate',
    'CRT',
    'KEY',
    'PFX',
  ),
  httpDns: flattenTerms(
    'DNS',
    'Override DNS',
    'DNS servers',
    'Host overrides',
  ),
  httpProxy: flattenTerms(
    'Proxy',
    'Enable proxy',
    'HTTP proxy',
    'HTTPS proxy',
    'Bypass list',
    'Route HTTP and HTTPS traffic through a proxy',
  ),
  privacy: flattenTerms(
    'Privacy',
    'Telemetry',
    'Send anonymous telemetry',
  ),
  about: flattenTerms(
    'Testrix',
    'About',
    'Runtime',
    'Updates',
    'Release channel',
    'Check for updates',
    'Check for updates on startup',
    'Restart to install',
    'View on GitHub',
    'Application',
    'Electron',
    'Chromium',
    'Platform',
    'Dev toolkit',
    'Stable',
    'Beta',
    'Product information',
  ),
};

const SETTINGS_SECTION_SEARCH_BLOBS: Record<SettingsPopupSection, string> = Object.fromEntries(
  (Object.entries(SETTINGS_SECTION_SEARCH_TERMS) as [SettingsPopupSection, readonly string[]][]).map(
    ([sectionId, terms]) => [sectionId, terms.join(' ').toLowerCase()],
  ),
) as Record<SettingsPopupSection, string>;

/**
 * Returns true when `query` matches sidebar metadata or any indexed option/label in the section.
 */
export function settingsSectionMatchesQuery(
  sectionId: SettingsPopupSection,
  query: string,
): boolean {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return true;
  }

  return SETTINGS_SECTION_SEARCH_BLOBS[sectionId].includes(normalized);
}
