CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sample_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders (id),
  sample_item_id INTEGER NOT NULL REFERENCES sample_items (id),
  qty INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS sample_items_name_idx ON sample_items (name);
CREATE INDEX IF NOT EXISTS customers_email_idx ON customers (email);
CREATE INDEX IF NOT EXISTS orders_created_at_idx ON orders (created_at);

CREATE OR REPLACE VIEW order_summaries AS
SELECT o.id AS order_id, c.name AS customer_name, COUNT(oi.id) AS item_count
FROM orders o
JOIN customers c ON c.id = o.customer_id
LEFT JOIN order_items oi ON oi.order_id = o.id
GROUP BY o.id, c.name;

CREATE OR REPLACE FUNCTION item_count(p_order_id INTEGER)
RETURNS INTEGER
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(SUM(qty), 0)::INTEGER FROM order_items WHERE order_id = p_order_id
$$;

CREATE OR REPLACE FUNCTION stamp_sample_items_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sample_items_set_updated_at ON sample_items;
CREATE TRIGGER sample_items_set_updated_at
BEFORE UPDATE ON sample_items
FOR EACH ROW
EXECUTE FUNCTION stamp_sample_items_updated_at();

DO $$
BEGIN
  CREATE ROLE testrix_ro LOGIN PASSWORD 'testrix';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

GRANT USAGE ON SCHEMA public TO testrix_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO testrix_ro;

INSERT INTO categories (name)
VALUES ('general'), ('tools')
ON CONFLICT (name) DO NOTHING;

INSERT INTO customers (email, name)
VALUES ('ada@example.com', 'Ada Lovelace'), ('alan@example.com', 'Alan Turing')
ON CONFLICT (email) DO NOTHING;

INSERT INTO sample_items (name, category_id)
SELECT v.name, c.id
FROM (VALUES
  ('alpha', 'general'),
  ('beta', 'general'),
  ('gamma', 'tools')
) AS v(name, category)
JOIN categories c ON c.name = v.category
WHERE NOT EXISTS (SELECT 1 FROM sample_items s WHERE s.name = v.name);

INSERT INTO orders (customer_id)
SELECT c.id
FROM customers c
WHERE c.email IN ('ada@example.com', 'alan@example.com')
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);

INSERT INTO order_items (order_id, sample_item_id, qty)
SELECT o.id, s.id, v.qty
FROM (VALUES
  ('ada@example.com', 'alpha', 2),
  ('ada@example.com', 'beta', 1),
  ('alan@example.com', 'gamma', 3)
) AS v(email, item, qty)
JOIN customers c ON c.email = v.email
JOIN orders o ON o.customer_id = c.id
JOIN sample_items s ON s.name = v.item
WHERE NOT EXISTS (
  SELECT 1 FROM order_items oi
  WHERE oi.order_id = o.id AND oi.sample_item_id = s.id
);
