import { existsSync } from 'node:fs';
import path from 'node:path';

import { bundledPath } from './paths';

/**
 * Window / taskbar icon generated by `npm run sync:brand`.
 */
export function resolveWindowIcon(): string | undefined {
  const candidates = [
    bundledPath('../src/assets/icon.ico'),
    bundledPath('../src/assets/icon.png'),
    path.join(process.resourcesPath, 'assets', 'icon.ico'),
    path.join(process.resourcesPath, 'assets', 'icon.png'),
    path.join(process.resourcesPath, 'icon.ico'),
  ];
  return candidates.find((item) => existsSync(item));
}

/**
 * Spread onto BrowserWindow options so every surface uses the Testrix mark.
 */
export function windowIconOption(): { readonly icon?: string } {
  const icon = resolveWindowIcon();
  return icon ? { icon } : {};
}
