import { existsSync } from 'node:fs';
import path from 'node:path';

import { bundledDir, bundledPath } from './paths';

function brandIconDirs(): readonly string[] {
  const resources = typeof process.resourcesPath === 'string' ? process.resourcesPath : '';
  const dirs: string[] = [
    bundledPath('../src/assets'),
    bundledPath('../build'),
    path.join(process.cwd(), 'assets', 'brand'),
    path.join(process.cwd(), 'apps', 'setup', 'src', 'assets'),
    path.join(process.cwd(), 'apps', 'setup', 'build'),
    path.join(process.cwd(), 'apps', 'desktop', 'src', 'assets'),
    path.join(process.cwd(), 'build'),
  ];
  if (resources) {
    dirs.push(path.join(resources, 'assets'), resources);
  }
  let dir = bundledDir();
  for (let i = 0; i < 6; i += 1) {
    dirs.push(path.join(dir, 'assets', 'brand'));
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return dirs;
}

/**
 * Window / taskbar icon generated by `npm run sync:brand`.
 */
export function resolveWindowIcon(): string | undefined {
  const names = ['icon.ico', 'icon.png'] as const;
  for (const folder of brandIconDirs()) {
    for (const name of names) {
      const file = path.join(folder, name);
      if (existsSync(file)) return file;
    }
  }
  return undefined;
}

/**
 * Spread onto BrowserWindow options so every surface uses the Testrix mark.
 */
export function windowIconOption(): { readonly icon?: string } {
  const icon = resolveWindowIcon();
  return icon ? { icon } : {};
}

/**
 * Applies the brand icon after the window exists (taskbar / Alt-Tab on Windows).
 */
export function applyWindowIcon(win: { readonly setIcon: (file: string) => void }): void {
  const icon = resolveWindowIcon();
  if (icon) win.setIcon(icon);
}
