export {
  APP_ID,
  MAIN_EXECUTABLE,
  PAYLOAD_MAGIC,
  PRODUCT_NAME,
  SETUP_APP_ID,
} from './identity';
export { IpcChannels, type IpcChannel } from './ipc-channels';
export {
  APPEARANCE_SETTING_KEYS,
  CONFIG_SCHEMA_VERSION,
  DEFAULT_SETTINGS_FILE,
  DEFAULT_USER_SETTINGS,
  FONT_MONO_OPTIONS,
  FONT_UI_OPTIONS,
  LOG_FILE_MAX_MB_DEFAULT,
  LOG_FILE_MAX_MB_MAX,
  LOG_FILE_MAX_MB_MIN,
  LOG_LEVEL_OPTIONS,
  TYPE_SCALE_OPTIONS,
  animationSpeedSchema,
  cloneDefaultUserSettings,
  fontMonoSchema,
  fontUiSchema,
  logLevelSchema,
  mergeUserSettingsPatch,
  parseSettingsFile,
  resolvedThemeSchema,
  settingsFileSchema,
  settingsResetScopeSchema,
  themePreferenceSchema,
  themeSnapshotSchema,
  toUserSettings,
  typeScaleSchema,
  userSettingsSchema,
  type AnimationSpeed,
  type FontMono,
  type FontUi,
  type LogLevel,
  type ResolvedTheme,
  type SettingsFile,
  type SettingsResetScope,
  type ThemePreference,
  type ThemeSnapshot,
  type TypeScale,
  type UserSettings,
} from './settings';
export {
  DEFAULT_CERTIFICATE_SETTINGS,
  DEFAULT_DNS_SETTINGS,
  DEFAULT_PROXY_SETTINGS,
  DNS_MODE_OPTIONS,
  PROXY_MODE_OPTIONS,
  certFileKindSchema,
  chooseFileKindSchema,
  certificateSettingsSchema,
  clientCertificateSchema,
  createClientCertificate,
  dnsModeSchema,
  dnsSettingsSchema,
  parseCertificateSettings,
  parseDnsSettings,
  parseProxySettings,
  proxyModeSchema,
  proxySettingsSchema,
  type CertificateSettings,
  type CertFileKind,
  type ChooseFileKind,
  type ClientCertificate,
  type DnsMode,
  type DnsSettings,
  type ProxyMode,
  type ProxySettings,
} from './network-settings';
export {
  DEFAULT_SHORTCUTS,
  SHORTCUT_CATALOG,
  shortcutIdSchema,
  shortcutsSchema,
  type ShortcutId,
  type Shortcuts,
} from './shortcuts';
export {
  DEFAULT_SELECTION_ENTRY,
  DEFAULT_SESSION_FILE,
  DEFAULT_SESSION_SELECTION,
  parseSessionFile,
  sanitizeSelectionEntry,
  sanitizeSessionForWorkspace,
  sessionEnvironmentNodeSelectionSchema,
  sessionFileSchema,
  sessionGroupSchema,
  sessionRailIdSchema,
  sessionSelectionEntrySchema,
  sessionSelectionSchema,
  sessionTabKindSchema,
  sessionTabSchema,
  type SessionEnvironmentNodeSelection,
  type SessionFile,
  type SessionGroup,
  type SessionRailId,
  type SessionSelection,
  type SessionSelectionEntry,
  type SessionTab,
} from './session';
export {
  CONFIG_FILE_NAMES,
  CONFIG_GLOBAL_FILES,
  CONFIG_WORKSPACE_FILES,
  DEFAULT_COLLECTIONS_FILE,
  collectionsFileSchema,
  configFileEntrySchema,
  configPathsSchema,
  configRevealTargetSchema,
  parseCollectionsFile,
  type CollectionsFile,
  type ConfigFileEntry,
  type ConfigFileName,
  type ConfigGlobalFileName,
  type ConfigPaths,
  type ConfigRevealTarget,
  type ConfigWorkspaceFileName,
} from './config-files';
export type { TestrixDesktopApi, TestrixErrorApi } from './preload-api';
export {
  SetupIpcChannels,
  type SetupDesktopApi,
  type SetupInstallRequest,
  type SetupMeta,
  type SetupMode,
  type SetupProgressEvent,
  type SetupScope,
  type SetupUninstallRequest,
} from './setup-api';
export { motionScaleForSpeed } from './motion';
export {
  COLLECTION_STATUS_FILTERS,
  DEFAULT_COLLECTION_FILTERS,
  DEFAULT_COLLECTION_PREFS,
  HTTP_METHODS,
  collectionFiltersSchema,
  collectionFolderNodeSchema,
  collectionHttpNodeSchema,
  collectionNodeKindSchema,
  collectionNodeSchema,
  collectionPrefsSchema,
  collectionSortModeSchema,
  collectionStatusFilterSchema,
  collectionTreeSchema,
  collectionWebSocketNodeSchema,
  httpMethodSchema,
  type CollectionFilters,
  type CollectionFolderNode,
  type CollectionHttpNode,
  type CollectionNode,
  type CollectionNodeKind,
  type CollectionPrefs,
  type CollectionSortMode,
  type CollectionStatusFilter,
  type CollectionTree,
  type CollectionWebSocketNode,
  type HttpMethod,
} from './collection-tree';
export {
  DEFAULT_ENVIRONMENT_PREFS,
  createDefaultEnvironments,
  createDefaultEnvironmentsFile,
  createDefaultVariables,
  environmentFolderSchema,
  environmentListSchema,
  environmentNodeSchema,
  environmentPrefsSchema,
  environmentSchema,
  environmentVariableCount,
  isEnvironmentNodeInactive,
  nextEnvironmentId,
  environmentVariableSchema,
  environmentsFileSchema,
  insertEnvironmentNode,
  insertEnvironmentNodeAt,
  isEnvironmentDescendant,
  isEnvironmentFolder,
  isEnvironmentVariable,
  mapEnvironmentNodes,
  moveEnvironmentNode,
  moveEnvironmentNodes,
  collectEnvironmentNodeIds,
  collectEnvironmentSecrets,
  environmentFolderCount,
  findEnvironmentFolder,
  findEnvironmentLocation,
  parseEnvironmentsFile,
  persistEnvironmentNodes,
  type Environment,
  type EnvironmentFolder,
  type EnvironmentList,
  type EnvironmentNode,
  type EnvironmentNodeLocation,
  type EnvironmentPrefs,
  type EnvironmentVariable,
  type EnvironmentsFile,
} from './environment';
export {
  DEFAULT_TOOLS,
  TOOL_IDS,
  isToolId,
  orderTools,
  parseToolOrderIds,
  toolById,
  toolIdSchema,
  type ToolId,
  type ToolItem,
} from './tools';
export {
  DATABASE_CONNECTION_MAX_FOLDER_DEPTH,
  DATABASE_CONNECTION_TAB_PREFIX,
  DATABASE_DEFAULT_PORTS,
  DATABASE_IDLE_DISCONNECT_MINUTES_DEFAULT,
  DATABASE_IDLE_DISCONNECT_MINUTES_MAX,
  DATABASE_IDLE_DISCONNECT_MINUTES_MIN,
  DATABASE_QUERY_TAB_PREFIX,
  DATABASE_TABLE_TAB_PREFIX,
  DATABASE_TYPE_IDS,
  DATABASE_TYPE_LABELS,
  DATABASE_UNCOMMITTED_ROLLBACK_SECONDS_DEFAULT,
  DATABASE_UNCOMMITTED_ROLLBACK_SECONDS_MAX,
  DATABASE_UNCOMMITTED_ROLLBACK_SECONDS_MIN,
  DEFAULT_DATABASES_FILE,
  DEFAULT_DATABASE_PREFS,
  DEFAULT_QUERIES_FILE,
  SAVED_QUERY_MAX_FOLDER_DEPTH,
  collectDatabaseSecrets,
  collectDatabaseTreeIds,
  collectQueryTreeIds,
  createDatabaseFolder,
  createDefaultDatabaseConnection,
  createDefaultSavedQuery,
  createQueryFolder,
  databaseConnectionFolderSchema,
  databaseConnectionSchema,
  databaseConnectionTabNodeId,
  databaseConnectionTreeItemSchema,
  databasePrefsSchema,
  databaseQueryTabNodeId,
  databaseSidebarFilterSchema,
  databaseSortModeSchema,
  databaseTableTabNodeId,
  databaseDiagramTabNodeId,
  databaseTypeSchema,
  databasesFileSchema,
  findDatabaseConnection,
  findDatabaseTreeItem,
  findQueryTreeItem,
  findSavedQuery,
  flattenDatabaseConnections,
  flattenSavedQueries,
  formatDatabaseConnectionString,
  isDatabaseConnectionFolder,
  isSavedQueryFolder,
  parseDatabaseConnectionString,
  parseDatabaseConnectionTabNodeId,
  parseDatabasePrefs,
  parseDatabaseQueryTabNodeId,
  parseDatabaseTableTabNodeId,
  parseDatabaseDiagramTabNodeId,
  parseDatabasesFile,
  parseQueriesFile,
  queriesFileSchema,
  savedDatabaseQuerySchema,
  savedQueryLastResultSchema,
  toSavedQueryLastResult,
  SAVED_QUERY_LAST_RESULT_MAX_COLUMNS,
  SAVED_QUERY_LAST_RESULT_MAX_ROWS,
  savedQueryFolderSchema,
  savedQueryTreeItemSchema,
  validDatabaseTabNodeIds,
  type DatabaseConnection,
  type DatabaseConnectionFolder,
  type DatabaseConnectionTreeItem,
  type DatabasePrefs,
  type DatabaseSidebarFilter,
  type DatabaseSortMode,
  type DatabaseTableTabTarget,
  type DatabaseDiagramTabTarget,
  type DatabaseType,
  type DatabasesFile,
  type ParsedDatabaseConnectionString,
  type QueriesFile,
  type SavedDatabaseQuery,
  type SavedQueryLastResult,
  type SavedQueryFolder,
  type SavedQueryTreeItem,
} from './database';
export {
  databaseErrorContext,
  formatDatabaseError,
  type DatabaseErrorContext,
} from './database-error';
export {
  DATABASE_QUERY_EXPORT_FORMATS,
  DATABASE_QUERY_PAGE_SIZE_DEFAULT,
  DATABASE_QUERY_PAGE_SIZES,
  addTableDataInsertRow,
  addTableDataInsertRows,
  applyTableDataCellEdit,
  applyTableDataRowDeletes,
  buildTableDataDisplayRows,
  buildTableDataSelectSql,
  buildRelationWhere,
  foreignKeyJumpByColumn,
  buildTableDmlStatements,
  canEditTableData,
  countDatabaseExecuteStatements,
  databaseEngineFamily,
  databaseQueryEditorLanguage,
  databaseQueryEditorLanguageLabel,
  databaseQueryEditorPlaceholder,
  emptyTableDataDraft,
  formatDatabaseQueryResult,
  isDestructiveSql,
  isFullDatabaseQuerySelection,
  isTableDataDraftDirty,
  isSqlTransactionEngine,
  isTransactionalWriteSql,
  shouldHoldSqlSession,
  sqlTransactionControl,
  normalizeDatabaseQueryResult,
  normalizeTableDataOrderBy,
  normalizeTableDataWhereFilter,
  qualifySqlTableName,
  quoteSqlIdentifier,
  refuseTableDml,
  resolveDatabaseExecuteHighlightRanges,
  resolveDatabaseExecuteQuery,
  shouldPromptDatabaseExecuteChooser,
  sqlLiteral,
  stripTrailingSqlSemicolons,
  tableDataOrderByError,
  tableDataPkIndexes,
  tableDataPkKey,
  tableDataPkValues,
  tableDataWhereFilterError,
  tableDmlBeginSql,
  tableDmlCommitSql,
  tableDmlRollbackSql,
  toggleTableDataDelete,
  type DatabaseCatalogColumn,
  type DatabaseCatalogForeignKey,
  type DatabaseRelationJump,
  type DatabaseCatalogIndex,
  type DatabaseCatalogRoutine,
  type DatabaseCatalogSequence,
  type DatabaseCatalogTable,
  type DatabaseCatalogTrigger,
  type DatabaseCatalogUser,
  type DatabaseConnectionStatus,
  type DatabaseConnectionStatusMap,
  type DatabaseConnectionStatusState,
  type DatabaseEngineFamily,
  type DatabaseExecuteChooserMode,
  type DatabaseExecuteLanguage,
  type DatabaseIntrospectLevel,
  type DatabaseIntrospectResult,
  type DatabaseQueryCell,
  type DatabaseQueryCellRange,
  type DatabaseQueryEditorLanguage,
  type DatabaseQueryEnvelope,
  type DatabaseQueryExportFormat,
  type DatabaseQueryRequest,
  type DatabaseQueryTable,
  type DatabaseSessionQueryRequest,
  type DatabaseSessionState,
  type SqlTransactionControl,
  type TableDataCell,
  type TableDataDisplayRow,
  type TableDataDraft,
  type TableDataRowKind,
  type TableDmlRefuseReason,
  type TableDmlStatement,
} from './database-sql';
export {
  LOG_RECENT_LINE_LIMIT,
  LOG_SECRET_MIN_LENGTH,
  LOG_SECRET_REDACTED,
  redactSecrets,
} from './log-redact';
export {
  CONFIGS_DIR,
  DEFAULT_WORKSPACE_FOLDER,
  DEFAULT_WORKSPACE_ID,
  DEFAULT_WORKSPACE_NAME,
  WORKSPACES_DIR,
  WORKSPACES_FILE_NAME,
  applyWorkspaceOrder,
  canDeleteWorkspace,
  createDefaultWorkspace,
  createDefaultWorkspacesFile,
  duplicateWorkspaceName,
  isDefaultWorkspace,
  nextWorkspaceFolder,
  nextWorkspaceId,
  parseWorkspacesFile,
  removeWorkspaceFromCatalog,
  resolveActiveWorkspace,
  shouldMigrateLegacyLayout,
  workspaceDisplayName,
  workspaceListSchema,
  workspaceSchema,
  workspacesFileSchema,
  type Workspace,
  type WorkspaceList,
  type WorkspaceSnapshot,
  type WorkspacesFile,
} from './workspace';
