/**
 * Typed IPC channel names for `window.testrix`.
 */
export const IpcChannels = {
  appGetVersion: 'testrix:app:getVersion',
  appGetPlatform: 'testrix:app:getPlatform',
  appNotifyReady: 'testrix:app:notifyReady',
  appReload: 'testrix:app:reload',
  windowMinimize: 'testrix:window:minimize',
  windowMaximize: 'testrix:window:maximize',
  windowClose: 'testrix:window:close',
  windowIsMaximized: 'testrix:window:isMaximized',
  windowSetMovable: 'testrix:window:setMovable',
  windowMaximizedChanged: 'testrix:window:maximizedChanged',
  themeGet: 'testrix:theme:get',
  themeSet: 'testrix:theme:set',
  themeChanged: 'testrix:theme:changed',
  settingsGet: 'testrix:settings:get',
  settingsSet: 'testrix:settings:set',
  settingsReset: 'testrix:settings:reset',
  sessionGet: 'testrix:session:get',
  sessionSet: 'testrix:session:set',
  environmentsGet: 'testrix:environments:get',
  environmentsSet: 'testrix:environments:set',
  collectionsGet: 'testrix:collections:get',
  collectionsSet: 'testrix:collections:set',
  databasesGet: 'testrix:databases:get',
  databasesSet: 'testrix:databases:set',
  queriesGet: 'testrix:queries:get',
  queriesSet: 'testrix:queries:set',
  databaseTest: 'testrix:database:test',
  databaseIntrospect: 'testrix:database:introspect',
  databaseQuery: 'testrix:database:query',
  databaseExplain: 'testrix:database:explain',
  databaseDisconnect: 'testrix:database:disconnect',
  databaseStatuses: 'testrix:database:statuses',
  databaseSessionQuery: 'testrix:database:sessionQuery',
  databaseSessionCommit: 'testrix:database:sessionCommit',
  databaseSessionRollback: 'testrix:database:sessionRollback',
  databaseSessionClose: 'testrix:database:sessionClose',
  databaseWarmBoot: 'testrix:database:warmBoot',
  workspacesGet: 'testrix:workspaces:get',
  workspacesSwitch: 'testrix:workspaces:switch',
  workspacesCreate: 'testrix:workspaces:create',
  workspacesRename: 'testrix:workspaces:rename',
  workspacesDuplicate: 'testrix:workspaces:duplicate',
  workspacesDelete: 'testrix:workspaces:delete',
  configPaths: 'testrix:config:paths',
  configReveal: 'testrix:config:reveal',
  configChooseFolder: 'testrix:config:chooseFolder',
  configChooseLogsFolder: 'testrix:config:chooseLogsFolder',
  configChooseConfigsFolder: 'testrix:config:chooseConfigsFolder',
  configChooseFile: 'testrix:config:chooseFile',
  logsRecent: 'testrix:logs:recent',
  splashSetStatus: 'testrix:splash:setStatus',
  errorQuit: 'testrix:error:quit',
  errorRelaunch: 'testrix:error:relaunch',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
