export const TeamChannels = {
  getStatus: 'team:getStatus',
  getConfig: 'team:getConfig',
  setConfig: 'team:setConfig',
  getGitSetup: 'team:getGitSetup',
  setRemote: 'team:setRemote',
  syncNow: 'team:syncNow',
  onFocus: 'team:onFocus',
  getHistory: 'team:getHistory',
  getCommitDiff: 'team:getCommitDiff',
  getCommitDetail: 'team:getCommitDetail',
  listBranches: 'team:listBranches',
  createBranch: 'team:createBranch',
  switchBranch: 'team:switchBranch',
  deleteBranch: 'team:deleteBranch',
  resolveConflict: 'team:resolveConflict',
  linkWorkspace: 'team:linkWorkspace',
  disconnect: 'team:disconnect',
  fetchRemoteCatalog: 'team:fetchRemoteCatalog',
  importProfiles: 'team:importProfiles',
  publishLocalProfile: 'team:publishLocalProfile',
  createTeamProfile: 'team:createTeamProfile',
  unpublishProfile: 'team:unpublishProfile',
  statusChanged: 'team:statusChanged',
  openPanel: 'team:openPanel',
  externalFileChanged: 'team:externalFileChanged',
  profilesMerged: 'team:profilesMerged',
} as const;
