export const TestingChannels = {
  getTestSuites: 'testing:getTestSuites',
  setTestSuites: 'testing:setTestSuites',
  getLoadTests: 'testing:getLoadTests',
  setLoadTests: 'testing:setLoadTests',
  getRegressions: 'testing:getRegressions',
  setRegressions: 'testing:setRegressions',
  getMockServer: 'testing:getMockServer',
  setMockServer: 'testing:setMockServer',
  getCapture: 'testing:getCapture',
  setCapture: 'testing:setCapture',
  getInterceptor: 'testing:getInterceptor',
  setInterceptor: 'testing:setInterceptor',
  mockStatus: 'testing:mockStatus',
  mockStart: 'testing:mockStart',
  mockStop: 'testing:mockStop',
  captureStatus: 'testing:captureStatus',
  captureStart: 'testing:captureStart',
  captureStop: 'testing:captureStop',
  captureListEntries: 'testing:captureListEntries',
  interceptorStatus: 'testing:interceptorStatus',
  interceptorStart: 'testing:interceptorStart',
  interceptorStop: 'testing:interceptorStop',
  loadTestStatus: 'testing:loadTestStatus',
  loadTestMetrics: 'testing:loadTestMetrics',
  loadTestStart: 'testing:loadTestStart',
  loadTestCancel: 'testing:loadTestCancel',
  e2eExecuteFlow: 'testing:e2eExecuteFlow',
  e2eCancel: 'testing:e2eCancel',
} as const;

export type TestingChannel = (typeof TestingChannels)[keyof typeof TestingChannels];
