/**
 * Stroke icons for Testrix UI (24×24 viewBox, `currentColor`).
 * Canonical artwork: `assets/icons/*.svg` (served at `/icons/`).
 */

/** Converts registry keys (`maximizeRestore`) to SVG file stems (`maximize-restore`). */
export function txIconFileStem(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** Public URL for a registry icon (Angular copies `assets/icons` → `/icons/`). */
export function txIconAssetUrl(name: TxIconName): string {
  return `/icons/${txIconFileStem(name)}.svg`;
}

export const TX_ICON_NAMES = [
  'minimize',
  'maximize',
  'maximizeRestore',
  'close',
  'settings',
  'settingsGear',
  'development',
  'testing',
  'help',
  'interceptor',
  'home',
  'search',
  'menu',
  'filter',
  'moreHorizontal',
  'moreVertical',
  'chevronLeft',
  'chevronRight',
  'chevronUp',
  'chevronDown',
  'arrowLeft',
  'arrowRight',
  'plus',
  'minus',
  'edit',
  'trash',
  'copy',
  'refresh',
  'download',
  'upload',
  'share',
  'externalLink',
  'link',
  'play',
  'pause',
  'stop',
  'record',
  'info',
  'warning',
  'error',
  'check',
  'checkCircle',
  'xCircle',
  'alertCircle',
  'code',
  'terminal',
  'bug',
  'gitBranch',
  'database',
  'cloud',
  'api',
  'http',
  'folder',
  'folderOpen',
  'file',
  'fileText',
  'user',
  'users',
  'logOut',
  'lock',
  'unlock',
  'eye',
  'eyeOff',
  'star',
  'bookmark',
  'bell',
  'calendar',
  'clock',
  'zap',
  'layers',
  'grid',
  'list',
  'box',
  'package',
  'target',
  'compass',
  'map',
  'wrench',
  'tool',
  'sliders',
  'toggleLeft',
  'toggleRight',
  'activity',
  'barChart',
  'pieChart',
  'clipboard',
  'tag',
  'hash',
  'globe',
  'mail',
  'message',
  'shield',
  'rocket',
] as const;

export type TxIconName = (typeof TX_ICON_NAMES)[number];
