/** Canonical wiki section ids — every id must have content in {@link HELP_WIKI_SECTIONS}. */
export const HELP_WIKI_SECTION_IDS = [
  // Overview
  'getting-started',
  'workspace-tabs',
  'sidebar-navigation',
  'profiles-data',
  // Collections
  'collections-tree',
  'http-requests',
  'request-overview',
  'request-params',
  'request-headers',
  'request-body',
  'request-auth',
  'request-scripts',
  'request-settings',
  'request-docs',
  'websockets',
  'collection-folders',
  'variables-placeholders',
  // Environments
  'environments-overview',
  'environment-variables',
  // Testing
  'testing-hub',
  'test-suite',
  'test-suite-steps',
  'load-test',
  'regression',
  'mock-server',
  'capture',
  'interceptor',
  // Development tools
  'dev-uuid-generator',
  'dev-code-editor',
  'dev-base64',
  'dev-jwt',
  'dev-cron',
  'dev-regex',
  'dev-url',
  'dev-bcrypt',
  'dev-openapi',
  // History
  'history',
  // Teams
  'teams-overview',
  'teams-branches',
  'teams-share-scope',
  // Settings reference
  'settings-appearance',
  'settings-ui',
  'settings-keyboard',
  'settings-collections',
  'settings-environments',
  'settings-test-suite',
  'settings-general',
  'settings-http-request',
  'settings-http-retries',
  'settings-http-testing',
  'settings-http-headers',
  'settings-http-certificates',
  'settings-http-dns',
  'settings-http-proxy',
  'settings-logging',
  'settings-databases',
  'settings-data-config',
  'settings-privacy',
  'settings-about',
  // Reference
  'ref-keyboard-shortcuts',
  'ref-dynamic-variables',
  'ref-local-first-paths',
  'ref-desktop-updates',
  'ref-tips-troubleshooting',
] as const;

export type HelpWikiSectionId = (typeof HELP_WIKI_SECTION_IDS)[number];
