-- Local Testrix Oracle seed (docker compose).
-- Connection from the Database sidebar: type Oracle, host localhost, port 1521,
-- user testrix, password testrix, service name FREEPDB1 (Use SID off).
-- Seed runs only on first volume create. Recreate with:
--   docker compose down -v && docker compose up -d

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR2(64) NOT NULL UNIQUE,
  name VARCHAR2(256) NOT NULL,
  price NUMBER(10, 2) NOT NULL,
  discontinued NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(128) NOT NULL,
  email VARCHAR2(256),
  bio VARCHAR2(512) DEFAULT '' NOT NULL,
  notes VARCHAR2(512),
  is_active NUMBER(1) DEFAULT 1 NOT NULL,
  balance NUMBER(10, 2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES users (id),
  product_id NUMBER NOT NULL REFERENCES products (id),
  quantity NUMBER NOT NULL,
  total NUMBER(10, 2) NOT NULL,
  status VARCHAR2(32),
  placed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO products (sku, name, price, discontinued) VALUES
  ('SKU-100', 'Notebook', 12.50, 0);
INSERT INTO products (sku, name, price, discontinued) VALUES
  ('SKU-200', 'Mechanical keyboard', 89.00, 0);
INSERT INTO products (sku, name, price, discontinued) VALUES
  ('SKU-300', 'USB-C hub', 34.99, 0);
INSERT INTO products (sku, name, price, discontinued) VALUES
  ('SKU-400', 'Legacy serial adapter', 19.00, 1);

INSERT INTO users (name, email, bio, notes, is_active, balance) VALUES
  ('User 1', 'user1@example.test', 'Bio for user 1', 'Note 1', 1, 10.25);
INSERT INTO users (name, email, bio, notes, is_active, balance) VALUES
  ('User 2', 'user2@example.test', 'Bio for user 2', NULL, 1, 20.50);
INSERT INTO users (name, email, bio, notes, is_active, balance) VALUES
  ('User 3', NULL, 'Bio for user 3', 'Note 3', 0, NULL);
INSERT INTO users (name, email, bio, notes, is_active, balance) VALUES
  ('User 4', 'user4@example.test', '', '', 1, 41.00);

INSERT INTO orders (user_id, product_id, quantity, total, status) VALUES
  (1, 1, 2, 25.00, 'shipped');
INSERT INTO orders (user_id, product_id, quantity, total, status) VALUES
  (2, 2, 1, 89.00, 'pending');
INSERT INTO orders (user_id, product_id, quantity, total, status) VALUES
  (1, 3, 1, 34.99, NULL);
INSERT INTO orders (user_id, product_id, quantity, total, status) VALUES
  (4, 4, 3, 57.00, 'cancelled');

COMMIT;
