ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = testrix;

CREATE TABLE IF NOT EXISTS testrix.categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS testrix.customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(128) NOT NULL UNIQUE,
  name VARCHAR2(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS testrix.sample_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(64) NOT NULL,
  category_id NUMBER NOT NULL REFERENCES testrix.categories (id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS testrix.orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL REFERENCES testrix.customers (id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS testrix.order_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER NOT NULL REFERENCES testrix.orders (id),
  sample_item_id NUMBER NOT NULL REFERENCES testrix.sample_items (id),
  qty NUMBER NOT NULL
);

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX sample_items_name_idx ON testrix.sample_items (name)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX customers_email_idx ON testrix.customers (email)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX orders_created_at_idx ON testrix.orders (created_at)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

CREATE OR REPLACE VIEW testrix.order_summaries AS
SELECT o.id AS order_id, c.name AS customer_name, COUNT(oi.id) AS item_count
FROM testrix.orders o
JOIN testrix.customers c ON c.id = o.customer_id
LEFT JOIN testrix.order_items oi ON oi.order_id = o.id
GROUP BY o.id, c.name;

CREATE OR REPLACE FUNCTION testrix.item_count(p_order_id NUMBER)
RETURN NUMBER
IS
  v_count NUMBER;
BEGIN
  SELECT COALESCE(SUM(qty), 0) INTO v_count FROM testrix.order_items WHERE order_id = p_order_id;
  RETURN v_count;
END;
/

CREATE OR REPLACE TRIGGER testrix.sample_items_set_updated_at
BEFORE UPDATE ON testrix.sample_items
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

INSERT INTO categories (name)
SELECT 'general' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'general');

INSERT INTO categories (name)
SELECT 'tools' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'tools');

INSERT INTO customers (email, name)
SELECT 'ada@example.com', 'Ada Lovelace' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'ada@example.com');

INSERT INTO customers (email, name)
SELECT 'alan@example.com', 'Alan Turing' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE email = 'alan@example.com');

INSERT INTO sample_items (name, category_id)
SELECT 'alpha', id FROM categories
WHERE name = 'general' AND NOT EXISTS (SELECT 1 FROM sample_items WHERE name = 'alpha');

INSERT INTO sample_items (name, category_id)
SELECT 'beta', id FROM categories
WHERE name = 'general' AND NOT EXISTS (SELECT 1 FROM sample_items WHERE name = 'beta');

INSERT INTO sample_items (name, category_id)
SELECT 'gamma', id FROM categories
WHERE name = 'tools' AND NOT EXISTS (SELECT 1 FROM sample_items WHERE name = 'gamma');

INSERT INTO orders (customer_id)
SELECT id FROM customers
WHERE email = 'ada@example.com'
  AND NOT EXISTS (
    SELECT 1 FROM orders o JOIN customers c ON c.id = o.customer_id WHERE c.email = 'ada@example.com'
  );

INSERT INTO orders (customer_id)
SELECT id FROM customers
WHERE email = 'alan@example.com'
  AND NOT EXISTS (
    SELECT 1 FROM orders o JOIN customers c ON c.id = o.customer_id WHERE c.email = 'alan@example.com'
  );

INSERT INTO order_items (order_id, sample_item_id, qty)
SELECT o.id, s.id, 2
FROM orders o
JOIN customers c ON c.id = o.customer_id
JOIN sample_items s ON s.name = 'alpha'
WHERE c.email = 'ada@example.com'
  AND NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id AND oi.sample_item_id = s.id);

INSERT INTO order_items (order_id, sample_item_id, qty)
SELECT o.id, s.id, 1
FROM orders o
JOIN customers c ON c.id = o.customer_id
JOIN sample_items s ON s.name = 'beta'
WHERE c.email = 'ada@example.com'
  AND NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id AND oi.sample_item_id = s.id);

INSERT INTO order_items (order_id, sample_item_id, qty)
SELECT o.id, s.id, 3
FROM orders o
JOIN customers c ON c.id = o.customer_id
JOIN sample_items s ON s.name = 'gamma'
WHERE c.email = 'alan@example.com'
  AND NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id AND oi.sample_item_id = s.id);

COMMIT;
